version: '3.1'

services:
  mongo-app-ms:
    image: mongo:3.6
    container_name: mongo-app-ctn
    ports:
      - "27017:27017"
    volumes:
      - mongo-app-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    networks:
      - net-app

volumes:
  mongo-app-volume:

networks:
  net-app:
